### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by aaghevli** [ResistanceCalendar/resistance-calendar-chrome-ext#3]
The full text of the event description copied in from the event page added at the end the end, the words "FACEBOOK LINK" which link to the page.

**Comment by aaghevli** [comment]
Fixed in https://github.com/ResistanceCalendar/resistance-calendar-chrome-ext/commit/7c51f07f2f923c3fdd0f38d5a703b390b9ea4338

**Comment by InciteDemocracy** [comment]
Currently we get something like this: "FACEBOOK LINK: http://facebook.com"
We want it to say "FACEBOOK LINK" and have that text link to the event page url.

**Comment by aaghevli** [comment]
Oops, yup. Fixed
